import streamlit as st
import sys
from pathlib import Path

# Add project root to sys.path to allow imports from src
root_path = Path(__file__).parent.parent.resolve()
if str(root_path) not in sys.path:
    sys.path.append(str(root_path))

from styles import load_css
from hero import hero
from upload import upload
from dashboard import dashboard

st.set_page_config(
    page_title="Resumatic",
    page_icon="📄",
    layout="wide",
    initial_sidebar_state="collapsed" # Hide sidebar completely by default
)

# Load custom CSS styles
st.markdown(load_css(), unsafe_allow_html=True)

# Define top header logo/navbar
def render_navbar():
    st.markdown("""
    <div class="navbar">
        <div class="logo-container">
            <span class="logo-icon">📄</span>
            <span>Resumatic</span>
        </div>
        <div class="nav-links">
            <a class="nav-link" href="#the-process">How it works</a>
        </div>
    </div>
    """, unsafe_allow_html=True)

# Define brand bar transition
def render_brand_bar():
    st.markdown("""
    <div class="white-section">
        <div class="brand-bar-title">Evaluation framework based on criteria used by</div>
        <div class="brand-links">
            <span class="brand-link-item">ATS Parsers</span>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <span class="brand-link-item">Recruiting Teams</span>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <span class="brand-link-item">Hiring Managers</span>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <span class="brand-link-item">Career Coaches</span>
        </div>
        <div id="the-process">
            <div class="process-pre">The Process</div>
            <div class="process-title">A structured evaluation, not generic advice</div>
            <div class="process-subtitle">
                Every resume is scored and reviewed across the same criteria a recruiting pipeline actually applies.
            </div>
        </div>
    </div>
    """, unsafe_allow_html=True)

# Define the 3-column process cards
def render_process_cards():
    col1, col2, col3 = st.columns(3)
    with col1:
        st.markdown("""
        <div class="process-card">
            <div class="process-card-icon">➕</div>
            <div class="process-card-title">Submit your resume</div>
            <div class="process-card-desc">Paste your resume text, or upload your PDF, and optionally include the target job description.</div>
        </div>
        """, unsafe_allow_html=True)
    with col2:
        st.markdown("""
        <div class="process-card">
            <div class="process-card-icon">📊</div>
            <div class="process-card-title">Automated evaluation</div>
            <div class="process-card-desc">Scored for ATS parsing, keyword coverage, structure, and impact — the same lenses a recruiter uses.</div>
        </div>
        """, unsafe_allow_html=True)
    with col3:
        st.markdown("""
        <div class="process-card">
            <div class="process-card-icon">✅</div>
            <div class="process-card-title">Prioritized fixes</div>
            <div class="process-card-desc">A ranked list of what to change first, with specific, actionable rewrites for each issue.</div>
        </div>
        """, unsafe_allow_html=True)
    st.write("")

# Define footer component
def render_footer():
    st.markdown("""
    <div class="footer-bar">
        <div class="footer-content">
            <span>© Resumatic — AI-assisted resume analysis</span>
            <span>Results are generated by AI and should be reviewed before use.</span>
        </div>
    </div>
    """, unsafe_allow_html=True)

# --- SINGLE PAGE LAYOUT FLOW ---

render_navbar()

# Hero & Upload Columns (Always visible on top)
hero_col, upload_col = st.columns([5, 4], gap="large")
with hero_col:
    hero()
with upload_col:
    resume_content, job_description, analyze_clicked = upload()

# Run the pipeline if "Analyze my resume" is clicked
if analyze_clicked and resume_content:
    st.session_state.target_job_description = job_description
    
    # 1. Parse resume text
    if hasattr(resume_content, "read"):
        from src.pdf_reader import extract_text_from_pdf
        resume_text = extract_text_from_pdf(resume_content)
    else:
        resume_text = resume_content
    st.session_state.resume_text = resume_text
    
    # 2. Predict Job Category
    with st.spinner("Classifying resume..."):
        from src.predictor import ResumePredictor
        predictor = ResumePredictor()
        category = predictor.predict(resume_text)
        st.session_state.predicted_category = category
        
    # 3. Extract Skills
    with st.spinner("Extracting resume skills..."):
        from src.skill_extractor import extract_skills
        skills = extract_skills(resume_text)
        st.session_state.skills = skills
        
    # 4. Compare with standard or dynamic Job Description
    with st.spinner("Performing skill gap analysis..."):
        if job_description:
            jd_skills = extract_skills(job_description)
            missing = [s for s in jd_skills if s not in skills]
            st.session_state.missing_skills = missing
            st.session_state.jd_skills_count = len(jd_skills)
        else:
            from missing_skills import get_missing_skills
            missing = get_missing_skills(category, skills)
            st.session_state.missing_skills = missing
            st.session_state.jd_skills_count = None
            
    # 5. Calculate ATS Score
    with st.spinner("Computing ATS score..."):
        from ats_calculator import calculate_ats
        score = calculate_ats(resume_text, skills)
        if job_description and st.session_state.jd_skills_count:
            match_ratio = (len(jd_skills) - len(missing)) / len(jd_skills)
            score = int((score * 0.4) + (match_ratio * 60))
        st.session_state.ats_score = score
        
    # 6. Generate Suggestions
    with st.spinner("Compiling recommendations..."):
        from suggestion_engine import generate_suggestions
        suggestions = generate_suggestions(score, missing)
        st.session_state.suggestions = suggestions
        
    st.session_state.analyzed = True
    st.rerun()

# Render Report Details DIRECTLY below the upload section if analyzed
if st.session_state.get("analyzed", False):
    dashboard()

# Render Footer
render_footer()